language: node_js
addons:
  sauce_connect: true
env:
  global:
  - secure: df9eTd6JkMOgdF3J3UInb0ouaDEbF4Y0sklmvwgBUs38yRvGQ3mucrzH13dCU0GYW8mM/H9euF7yG4/leWQHoUYdRJTDRy/sWXGvs6qg7DTkUXsmGyzv/5XxS86WTD5B9LbzB1hvRs5nzWeA1sFP6rpzGG6HwogM/+37ijRjKQQ=
  - secure: FI6ATM3Pngx0bowuYi5WHIDCe0R5ORlJWNsFxJyZLEusie+wZrRy9QbZsVvJGVYZJKAR9MFT3Ks494ou85lyfUnfvEnn+lX2DQ3Hsyz0xyBNoSvNkQbhZEsUr0TV+UGpCvSwYr6lYqXsBy6VxqyAkXDkqdVTAzMydq5ttGxszPU=
node_js:
  - '0.10'
before_script:
  - npm install grunt-saucelabs@8.5.x
  - npm install grunt-contrib-connect@0.9.x
  - npm install -g bower
  - npm install -g testem
  - npm install -g grunt-cli
  - npm install
  - make
script:
  - testem ci
  - grunt sauce
