language: node_js
env:
  matrix:
    - TARGET=saucelabs
    - TARGET=HeadlessFirefox
    - TARGET=HeadlessChrome
node_js:
  - 14
before_script:
  - npm install -g grunt-cli
  - grunt
script:
  - export COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  - export TRAVIS_CI=1
  - if [[ "${TARGET}" == "HeadlessFirefox" ]]; then npm test || exit 1; fi
  - if [[ "${TARGET}" == "HeadlessChrome" ]]; then npm test || exit 1; fi
  - if [[ "${TARGET}" == "saucelabs" ]]; do export SAUCELABS_BATCH=1; echo "Starting batch 1 of 2"; npm test; fi
  - if [[ "${TARGET}" == "saucelabs" ]]; do export SAUCELABS_BATCH=2; echo "Starting batch 2 of 2"; npm test; fi
